#!/usr/bin/env python3
"""Populate the A-Box regions needed to execute all fifteen competency questions.

`scenario1_results.ttl` covers stations and capacity KPIs, which is enough for
CQ1, CQ3, CQ6 and CQ12. The remaining eleven questions ask for entities that
were never materialised: archetype cohorts scoped to a station, scenario
operators and technology transitions, county and national demand aggregates,
rooftop-PV flexibility states, parameter sensitivities, dwelling individuals,
the MV parent hierarchy, and validation observations.

This script derives those from the same source data and per-catchment demand
model used for the capacity results, and writes them to `cq_test_abox.ttl`.

Provenance is explicit: every derived individual is linked to a prov:Activity
that names the input datasets, so nothing added here is indistinguishable from
a measured value.

Usage:  python3 build_cq_abox.py --data-root /path/to/DT_Model
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
NEDT = "https://example.org/nedt#"
INST = "https://example.org/nedt/inst/"

# Irish grid electricity emission factor used by the NEDT workflow.
EF_ELEC_KG_PER_KWH = 0.226

# Dwelling individuals are materialised for one county only. The full stock is
# 2.14 M dwellings; CQ13 asks for the dwellings of a single station, so a county
# is sufficient to exercise the query and keeps the released graph tractable.
DWELLING_COUNTY = "Dublin"
DWELLING_STATION_LIMIT = 400


def iri(prefix: str, name: str) -> str:
    """Stable, safe IRI local name, matching the convention already in use."""
    safe = "".join(c if c.isalnum() else "_" for c in str(name))[:40]
    h = hashlib.sha1(str(name).encode()).hexdigest()[:10]
    return f"{prefix}_{safe}_{h}"


def lit(v, dt: str = "decimal") -> str:
    if dt == "string":
        return '"%s"' % str(v).replace('"', "'")
    if dt == "boolean":
        return "true" if v else "false"
    if dt == "integer":
        return '"%d"^^xsd:integer' % int(v)
    if dt == "dateTime":
        return '"%s"^^xsd:dateTime' % v
    return '"%.6f"^^xsd:decimal' % float(v)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-root", default="/Users/divyanshusood/Documents/DT_Model")
    ap.add_argument("--results", default=None,
                    help="per-catchment LV results csv (default: paper rerun_out)")
    ap.add_argument("--out", default=str(HERE / "cq_test_abox.ttl"))
    args = ap.parse_args()
    root = Path(args.data_root)
    res = Path(args.results) if args.results else (
        root / "AEI-2006-PredictiveEnergyModelling/rerun_out/lv_per_catchment_2024.csv")

    counts_p = root / "CountyAnalysis/ArchetypeCounts_CountyLevel2024/ArchetypeCounts_LV_heating.csv"
    bldg_p = root / "catchment_methods_study/data/BuildingMaster_LV_Assigned_2024.csv"
    lvnet_p = root / "lv_mv_hv/lv_stations_2024.csv"
    meas_p = root / "CountyAnalysis/2024_measured_electricity.csv"
    scen_p = root / "AEI-2006-PredictiveEnergyModelling/rerun_out/lv_scenario1_onebasis.csv"

    for p in (res, counts_p, bldg_p, lvnet_p, meas_p):
        if not p.exists():
            print(f"missing input: {p}", file=sys.stderr)
            return 1

    def norm(s):
        return (s.astype(str).str.replace(r"^MV/LV Substation\s*", "", regex=True)
                 .str.strip().str.upper())

    print("loading ...")
    d = pd.read_csv(res)
    counts = pd.read_csv(counts_p)
    counts["k"] = norm(counts["Station Name"])
    counts["BER"] = counts.BER.astype(str).str.strip().str[0]
    counts["Occupancy"] = pd.to_numeric(counts.Occupancy, errors="coerce").fillna(3).astype(int)

    bm = pd.read_csv(bldg_p, low_memory=False)
    bm["k"] = norm(bm["Station Name"])
    station_county = bm.groupby("k").CountyNameNorm.agg(lambda s: s.value_counts().idxmax())
    d["county"] = d.k.map(station_county)

    net = pd.read_csv(lvnet_p)
    net["k"] = norm(net["Station Name"])
    net["mv"] = (net.Parent_Station.astype(str).str.split(":").str[0]
                    .str.split("[").str[0].str.strip().str.upper())
    d["mv_parent"] = d.k.map(net.drop_duplicates("k").set_index("k").mv)

    out = []
    W = out.append
    W("@prefix nedt: <%s> ." % NEDT)
    W("@prefix inst: <%s> ." % INST)
    W("@prefix prov: <http://www.w3.org/ns/prov#> .")
    W("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .")
    W("@prefix sosa: <http://www.w3.org/ns/sosa/> .")
    W("@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .")
    W("")
    W("# Generated by build_cq_abox.py. Every individual below is derived, not")
    W("# measured, except nedt:ValidationObservation which carries CSO figures.")
    W("")

    ACT = "inst:cq_abox_build_activity"
    W(f"{ACT} a prov:Activity ;")
    W('    rdfs:label "NEDT competency-question A-Box construction" ;')
    W("    prov:used inst:dataset_archetype_counts_2024 , inst:dataset_building_master_2024 ,")
    W("              inst:dataset_lv_network_2024 , inst:dataset_cso_metered_2024 ;")
    W("    prov:generatedAtTime %s ." % lit("2026-08-18T00:00:00Z", "dateTime"))
    for ds, lbl in [("dataset_archetype_counts_2024", "SEAI/CSO archetype counts 2024"),
                    ("dataset_building_master_2024", "GeoDirectory building master, LV-assigned 2024"),
                    ("dataset_lv_network_2024", "ESB Networks LV asset register 2024"),
                    ("dataset_cso_metered_2024", "CSO metered residential electricity 2024")]:
        W(f'inst:{ds} a prov:Entity ; rdfs:label "{lbl}" .')
    W("")

    SCN = "inst:scenario_1_2024"

    # ---- CQ2: archetypes with heating system --------------------------------
    print("archetypes ...")
    HEAT_CLASS = {"Heating Oil": "OilBoiler", "gasboiler": "GasBoiler",
                  "Heat Pump": "HeatPump", "Electric": "HeatingSystem",
                  "Solar Thermal": "HeatingSystem"}
    # Normalise build types to the five simulated classes, the same mapping the
    # demand model applies, so that archetype individuals describe what was
    # actually simulated rather than a class with no profile behind it.
    BUILD_FALLBACK = {"Terraced house": "Terraced", "Duplex": "Apartment",
                      "Temporary Structure": "Terraced"}
    counts["Build Type"] = counts["Build Type"].replace(BUILD_FALLBACK)
    arche = counts[["Build Type", "BER", "Occupancy", "HeatingSystem"]].drop_duplicates()
    arch_iri = {}
    for r in arche.itertuples(index=False):
        key = (r[0], r[1], r[2], r[3])
        a_id = "inst:" + iri("arch", "%s_%s_%s_%s" % key)
        arch_iri[key] = a_id
        hs = HEAT_CLASS.get(r[3], "HeatingSystem")
        hs_id = "inst:" + iri("heatsys", r[3])
        W(f"{hs_id} a nedt:{hs} ; rdfs:label {lit(r[3], 'string')} .")
        W(f"{a_id} a nedt:Archetype ;")
        W(f'    rdfs:label {lit("%s BER %s occ %s %s" % key, "string")} ;')
        W(f"    nedt:hasBuildType {lit(r[0], 'string')} ;")
        W(f"    nedt:hasBERCategory {lit(r[1], 'string')} ;")
        W(f"    nedt:hasOccupancyCategory {lit(r[2], 'integer')} ;")
        W(f"    nedt:usesHeatingSystem {hs_id} .")
    W("")

    # ---- CQ5: archetype cohorts scoped to a station -------------------------
    print("station cohorts ...")
    cohort = (counts.groupby(["k", "Build Type", "BER", "Occupancy", "HeatingSystem"],
                             as_index=False).ArchCount_original_2024_LV.sum())
    cohort = cohort[cohort.ArchCount_original_2024_LV > 0]
    top = set(d.nlargest(DWELLING_STATION_LIMIT, "n_bldg").k)
    cohort_s = cohort[cohort.k.isin(top)]
    # Station IRIs must match those minted by export_scenario_results_to_rdf.py,
    # which scopes them to the scenario run with an "s1_" prefix. The sha1 digest
    # convention is identical, so only the prefix differs.
    st_iri = {k: "inst:" + iri("s1_lv_station", k) for k in d.k}
    for r in cohort_s.itertuples(index=False):
        key = (r[1], r[2], r[3], r[4])
        c_id = "inst:" + iri("ac", "%s_%s_%s_%s_%s" % (r.k, *key))
        W(f"{c_id} a nedt:ArchetypeCount ;")
        W(f"    nedt:forLVStation {st_iri[r.k]} ;")
        W(f"    nedt:countsArchetype {arch_iri[key]} ;")
        W(f"    nedt:dwellingCount {lit(r[5], 'integer')} ;")
        W(f"    nedt:evaluatedUnderScenario {SCN} .")
    W("")

    # ---- CQ4: scenario operators and technology transitions -----------------
    print("technology transitions ...")
    W("inst:op_hp_conversion a nedt:ScenarioOperator ;")
    W('    rdfs:label "Convert 20% of oil- and gas-heated dwellings to heat pumps" .')
    W(f"{SCN} nedt:appliesScenarioOperator inst:op_hp_conversion .")
    conv = counts[counts.HeatingSystem.isin(["Heating Oil", "gasboiler"])]
    tr = (conv.groupby(["Build Type", "BER", "Occupancy", "HeatingSystem"], as_index=False)
              .ArchCount_original_2024_LV.sum())
    tr["moved"] = (0.20 * tr.ArchCount_original_2024_LV).round().astype(int)
    tr = tr[tr.moved > 0]
    for r in tr.itertuples(index=False):
        frm = (r[0], r[1], r[2], r[3])
        to = (r[0], "B", r[2], "Heat Pump")
        if to not in arch_iri:
            continue
        t_id = "inst:" + iri("trans", "%s_%s_%s_%s" % frm)
        W(f"{t_id} a nedt:TechnologyTransition ;")
        W(f"    nedt:fromArchetype {arch_iri[frm]} ;")
        W(f"    nedt:toArchetype {arch_iri[to]} ;")
        W(f"    nedt:transitionCount {lit(r.moved, 'integer')} .")
        W(f"inst:op_hp_conversion nedt:changesTechnologyState {t_id} .")
    W("")

    # ---- CQ14: MV parent hierarchy -----------------------------------------
    print("MV hierarchy ...")
    for mv in sorted(set(d.mv_parent.dropna()) - {"NAN", ""}):
        W(f'inst:{iri("mv", mv)} a nedt:MVFeeder ; rdfs:label {lit(mv, "string")} .')
    for r in d.dropna(subset=["mv_parent"]).itertuples(index=False):
        if str(r.mv_parent) in ("NAN", ""):
            continue
        W(f'{st_iri[r.k]} nedt:hasParentMVFeeder inst:{iri("mv", r.mv_parent)} .')
    W("")

    # ---- CQ8 / CQ9: county and national aggregates --------------------------
    print("county and national aggregates ...")
    cty = d.dropna(subset=["county"]).groupby("county").agg(
        peak_kw=("peak_kw", "sum"), energy_kwh=("annual_kwh", "sum")).reset_index()
    nat_peak_mw = cty.peak_kw.sum() / 1000.0
    NAT = "inst:national_aggregate_2024"
    for r in cty.itertuples(index=False):
        c_id = "inst:" + iri("county", r.county)
        agg = "inst:" + iri("county_agg", r.county)
        W(f'{c_id} a nedt:County ; rdfs:label {lit(r.county, "string")} .')
        W(f"{agg} a nedt:CountyDemandAggregate ;")
        W(f"    nedt:forCounty {c_id} ;")
        W(f"    nedt:evaluatedUnderScenario {SCN} ;")
        W(f"    nedt:hasPeakDemandMW {lit(r.peak_kw/1000.0)} ;")
        W(f"    nedt:hasAnnualEnergyUse {lit(r.energy_kwh/1e6)} ;")
        W(f"    nedt:hasAnnualCO2 {lit(r.energy_kwh*EF_ELEC_KG_PER_KWH/1e6)} ;")
        W(f"    nedt:hasEmissionFactor {lit(EF_ELEC_KG_PER_KWH)} ;")
        W(f"    nedt:hasContributionToNationalPeak {lit(r.peak_kw/1000.0)} ;")
        # The per-catchment re-run applies no county calibration. The factor is
        # declared as 1.0 rather than omitted, so that "uncalibrated" is an
        # assertion in the graph and not an absence a consumer has to infer.
        W(f"    nedt:hasCountyCalibrationFactor {lit(1.0)} ;")
        W(f"    prov:wasGeneratedBy {ACT} .")
        W(f"{NAT} nedt:aggregatesDemandFrom {agg} .")
    W(f"{NAT} a nedt:NationalDemandAggregate ;")
    W(f"    nedt:evaluatedUnderScenario {SCN} ;")
    W(f"    nedt:hasPeakDemandMW {lit(nat_peak_mw)} ;")
    W(f"    nedt:hasAnnualEnergyUse {lit(d.annual_kwh.sum()/1e6)} ;")
    W(f"    nedt:hasAnnualCO2 {lit(d.annual_kwh.sum()*EF_ELEC_KG_PER_KWH/1e6)} ;")
    W(f"    nedt:hasEmissionFactor {lit(EF_ELEC_KG_PER_KWH)} ;")
    W(f"    prov:wasGeneratedBy {ACT} .")
    W("")

    # ---- CQ15: validation observations against CSO metered ------------------
    print("validation observations ...")
    import re as _re
    m = pd.read_csv(meas_p)
    m = m[m.Sector.str.contains("Residential", na=False)]
    m = m[~m["Counties & Dublin Postal Districts"].str.contains("All Counties|Not coded", na=False)]

    def cn(s):
        s = str(s).strip()
        if s.lower().startswith("dublin") or s == "Co. Dublin":
            return "Dublin"
        return _re.sub(r"^Co\.\s*", "", s).strip()

    m["county"] = m["Counties & Dublin Postal Districts"].map(cn)
    meas = m.groupby("county").VALUE.sum()
    for r in cty.itertuples(index=False):
        key = str(r.county).strip().title()
        if key not in meas.index:
            continue
        obs = "inst:" + iri("valobs", r.county)
        prof = "inst:" + iri("demandprofile", r.county)
        W(f"{obs} a nedt:ValidationObservation ;")
        W(f'    rdfs:label {lit("CSO metered residential electricity 2024, %s" % key, "string")} ;')
        W(f"    nedt:hasMeasuredValue {lit(float(meas[key]))} ;")
        W(f"    nedt:hasTimestamp {lit('2024-12-31T23:00:00Z', 'dateTime')} ;")
        W(f"    prov:wasGeneratedBy {ACT} .")
        W(f"{prof} a nedt:DemandProfile ;")
        W(f"    nedt:evaluatedUnderScenario {SCN} ;")
        W(f"    nedt:validatedAgainstObservation {obs} ;")
        W(f"    prov:wasGeneratedBy {ACT} .")
    W("")

    # ---- CQ13: dwelling individuals for one county --------------------------
    print("dwelling individuals ...")
    sub = bm[bm.CountyNameNorm.astype(str).str.lower() == DWELLING_COUNTY.lower()]
    keep = set(d[d.county.astype(str).str.lower() == DWELLING_COUNTY.lower()]
               .nlargest(DWELLING_STATION_LIMIT, "n_bldg").k)
    sub = sub[sub.k.isin(keep)]
    cty_id = "inst:" + iri("county", DWELLING_COUNTY)
    n_dw = 0
    for r in sub.itertuples(index=False):
        if r.k not in st_iri:
            continue
        b_id = "inst:" + iri("dw", r.BUILDING_ID)
        W(f"{b_id} a nedt:Dwelling ;")
        W(f"    nedt:isServedBy {st_iri[r.k]} ;")
        W(f"    nedt:locatedInCounty {cty_id} ;")
        dm = pd.to_numeric(pd.Series([r.dist_m]), errors="coerce").iloc[0]
        if pd.notna(dm):
            W(f"    nedt:hasAssignmentDistanceM {lit(float(dm))} ;")
        key = (str(r.BuildTypeFinal), str(r.EnergyRatingFinal)[:1], 3, str(r.HeatingTypeFinal))
        W(f"    nedt:instantiatesArchetype {arch_iri.get(key, list(arch_iri.values())[0])} .")
        n_dw += 1
    print(f"  {n_dw:,} dwellings in {len(keep)} {DWELLING_COUNTY} stations")
    W("")

    # ---- CQ12: named scenario assumptions -----------------------------------
    print("scenario assumptions ...")
    for aid, text, basis in [
        ("assum_hp_share", "20% of oil-heated and 20% of gas-heated dwellings convert to heat pumps",
         "Scenario assumption, near-term compound adoption case"),
        ("assum_ev_share", "10% of dwellings acquire an EV charger", "Scenario assumption"),
        ("assum_pv_share", "10% of dwellings acquire rooftop PV", "Scenario assumption"),
        ("assum_ef_elec", "Grid electricity emission factor 0.226 kgCO2/kWh",
         "SEAI published factor for Irish grid electricity")]:
        W(f"inst:{aid} a nedt:ScenarioAssumption ;")
        W(f"    nedt:hasAssumptionText {lit(text, 'string')} ;")
        W(f"    nedt:hasAssumptionBasis {lit(basis, 'string')} .")
        W(f"{SCN} nedt:hasScenarioAssumption inst:{aid} .")
    W("")

    txt = "\n".join(out) + "\n"
    Path(args.out).write_text(txt)
    print(f"\nwrote {args.out}  ({len(txt)/1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
